image_tag: "2025.1-ubuntu_noble_uv"
distro_image: "public.ecr.aws/ubuntu/ubuntu:noble"
openstack_release: "stable/2025.1"
# NOTE: Ubuntu Noble provides Ceph Squid packages out of the box
ceph_repo: ""
openstack_images:
  - "{{ barbican_image }}"
  - "{{ blazar_image }}"
  - "{{ ceilometer_image }}"
  - "{{ cinder_image }}"
  - "{{ cloudkitty_image }}"
  - "{{ cyborg_image }}"
  - "{{ designate_image }}"
  - "{{ freezer_image }}"
  - "{{ freezer_api_image }}"
  - "{{ glance_image }}"
  - "{{ heat_image }}"
  - "{{ horizon_image }}"
  - "{{ ironic_image }}"
  - "{{ keystone_image }}"
  - "{{ magnum_image }}"
  - "{{ manila_image }}"
  - "{{ masakari_image }}"
  - "{{ masakari_monitors_image }}"
  - "{{ mistral_image }}"
  - "{{ neutron_image }}"
  - "{{ nova_image }}"
  - "{{ octavia_image }}"
  - "{{ openstack_client_image }}"
  - "{{ placement_image }}"
  - "{{ swift_image }}"
  - "{{ tacker_image }}"
  - "{{ trove_image }}"
  - "{{ watcher_image }}"
  - "{{ zaqar_image }}"
