image_tag: "2023.2-ubuntu_jammy"
distro_image: "ubuntu:jammy"
openstack_release: "stable/2023.2"
ceph_repo: "deb https://download.ceph.com/debian-reef/ jammy main"
openstack_images:
  - "{{ barbican_image }}"
  - "{{ cinder_image }}"
  - "{{ cyborg_image }}"
  - "{{ designate_image }}"
  - "{{ glance_image }}"
  - "{{ heat_image }}"
  - "{{ horizon_image }}"
  - "{{ ironic_image }}"
  - "{{ keystone_image }}"
  - "{{ manila_image }}"
  - "{{ monasca_api_image }}"
  - "{{ neutron_image }}"
  - "{{ nova_image }}"
  - "{{ octavia_image }}"
  - "{{ placement_image }}"
  - "{{ tacker_image}}"
  - "{{ watcher_image }}"
